In [2]:
import numpy as np

l = [1,2,3,4] #python list
a=np.array([1,2,3,4]) #Numpy array

print(l, type(l))
print(a,type(a))

[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


In [3]:
#broadcasting
a+1
#but this cant be directly done by python list and  we will have to apply loop

array([2, 3, 4, 5])

In [4]:
b = np.array([[1,2,3],
             [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
b.shape


(2, 3)

In [6]:
b = b.reshape((6,1))  #2 D array
print(b)
print(b[0][0])

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
1


In [7]:
b = b.reshape((6,))
print (b)

[1 2 3 4 5 6]


In [8]:
b = b.reshape((3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
a = np.zeros((5,4), dtype='int')
print(a)
print(a.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [10]:
#updating a certaiin column
#here tht colum = 7
a[:,-1]=7
print(a)

[[0 0 0 7]
 [0 0 0 7]
 [0 0 0 7]
 [0 0 0 7]
 [0 0 0 7]]


In [11]:
#matrix of 1
b = np.ones((5,4),dtype='int')*6
print(b)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [12]:
c=np.eye((5),dtype='int')*5
print(c)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


In [13]:
c.T

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

In [14]:
print(c.T)  #for taking transpose

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


In [15]:
arr = np.array([12, 13, 14 ])
print(arr.max())
print(arr.min())
print(arr.argmax()) #returns index of maximum element
print(arr.mean())


14
12
2
13.0


In [16]:
### Random numbers

In [17]:
no = np.round(np.random.random())*5+8


In [18]:
no

13.0

In [19]:
no

13.0

In [20]:
no

13.0

In [21]:
np.random.randint(10,100,size=(2,3))

array([[91, 94, 19],
       [47, 43, 50]])

In [22]:
 np.random.randn(3,4) #normal distribution

array([[ 0.78066573,  0.13177804, -1.17181131, -1.00283161],
       [-0.26317134, -0.13817107, -1.56775386, -1.0297601 ],
       [ 0.03451183, -0.4298166 , -0.09885553, -2.11263081]])

In [23]:
arr.mean()

13.0

In [24]:
arr.std()

0.816496580927726

In [25]:
arr.shape

(3,)

In [26]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[1,2,3]]).reshape((3,1))
print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]]


In [27]:
print('hello')


hello


In [28]:
arr1.shape

(2, 3)

In [29]:
arr1.shape

(2, 3)

In [30]:
np.dot(arr1,arr2) #matrix dot product

array([[14],
       [32]])

In [31]:
arr1 = np.random.randint(0,100,size=(5,5)) #for generating sqaure matrix
print(arr1)

[[71 98 53 26 88]
 [15 49 64 36 74]
 [86  4 65  9 65]
 [ 2 93 65 48  9]
 [31 42 19 31 31]]


In [32]:
np.linalg.inv(arr1)

array([[ 0.00093773, -0.0141007 ,  0.0089747 ,  0.00063836,  0.01199454],
       [ 0.01291108, -0.006578  , -0.00637534,  0.00496164, -0.00902132],
       [-0.00382525,  0.00329781,  0.00999808,  0.0114883 , -0.02131245],
       [-0.02074857,  0.00606855, -0.00042905, -0.002047  ,  0.04590685],
       [ 0.00466291,  0.01492304, -0.00603595, -0.0123548 , -0.00035842]])